server:
  port: 8287
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  #web:
  #resources:
  #static-locations:
  #- file:///C:\
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: 1000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flow-pre_assignment?serverTimezone=Asia/Seoul
    username: sbsst
    password: sbs123414

  jpa:
    hibernate:
      #ddl-auto: create #create update none
      show-sql: true
      format_sql: true
      use_sql_comments: true

